### ISSUE TITLE
Option to remove Horizon?

### ISSUE THREAD

**Issue by brandyyn** [kotmatross28729/Shader-fixer#10]
when playing without shaders i always turn off the sky in optifine because flying up a little bit will show a blue ugly square known at the horizon, disabling the sky removes that and makes it so the entire skybox is your custom sky

this is with "sky" turned on:
![image](https://github.com/user-attachments/assets/27d03796-5aa1-4283-b0a5-5fcb3f20b3ea)

this is with sky turned off:
![image](https://github.com/user-attachments/assets/c0e430b6-d490-4b24-8639-988ae7b4ab69)

but shaders look horrible with the sky off and all i want to do is remove the horizon, so if that could be an option i'd really appreciate that

**Comment by kotmatross28729** [comment]
I didn't quite understand "remove horizon" 

The horizon is the same sky that you turn off with optifine. 

A shader skybox is essentially just a modification of this “horizon”.

"Option to remove Horizon" is turning off the sky in the optifine settings

**Comment by brandyyn** [comment]
> I didn't quite understand "remove horizon"
> 
> The horizon is the same sky that you turn off with optifine.
> 
> A shader skybox is essentially just a modification of this “horizon”.
> 
> "Option to remove Horizon" is turning off the sky in the optifine settings

the sky above you with shaders has a cutoff point, like its being stitched together when the sky is turned off in optifine settings, it works fine without shaders but when you turn shaders on you can see a very obvious visible stitching line

**Comment by kotmatross28729** [comment]
like this:
![2024-12-09_21 43 53](https://github.com/user-attachments/assets/ccd54fd7-0ee8-4d40-b161-7d70732b12da)


?





If yes, then this is precisely because you disabled the sky in the optifine settings, since shaders cannot modify the skybox correctly, since the one they modify is disabled




 This, as far as I know, should work fine in angelica (in sodium (iris) the skybox renderer doesn't modify the sky, but completely overwrites it, which accordingly means that it is independent of whether it is enabled or not)

**Comment by brandyyn** [comment]
yeah that's what i'm talking about, but i just want to remove the horizon cutoff and not affect the rest of the sky.

i use optifine because angelica doesn't yet have the features i need and i use coloured lighting with is incompatible.

**Comment by kotmatross28729** [comment]
> yeah that's what i'm talking about, but i just want to remove the horizon cutoff and not affect the rest of the sky.

The "horizon cutoff" occurs because the shaders need to connect the bottom and top of the skybox, to do this (in optifine) they modify the vanilla sky. When you turn off the sky in the optifine settings, you turn off this stitching, which is why it looks so weird. It is impossible to have a disabled sky and a connected skybox in optifine, because by disabling the sky in the settings, you are literally disabling the wall for stitching the bottom and top of the skybox, this is the intended behavior.


When you play without shaders, disable the sky, and when you enable shaders, just enable the sky in settings

**Comment by brandyyn** [comment]
sky off
![image](https://github.com/user-attachments/assets/e9a6e255-e106-4197-8e42-1624afef0491)

sky on
![image](https://github.com/user-attachments/assets/4a256a26-9a53-427b-8375-34382f88cc7e)


i just want that cut off point there where the moon is removed

**Comment by kotmatross28729** [comment]
Like I said, this is not possible in optifine, that's how it works (literally, optifine really works "specifically"). The only thing you can do is wait until angelica has the features/compatibility you need.
