### ISSUE TITLE
Request: add compatibility between shaders and Schematica

### ISSUE THREAD

**Issue by huihiuhuai** [kotmatross28729/Shader-fixer#2]

**Comment by kotmatross28729** [comment]
Should be fixed in 2.1
![2024-06-09_13 00 51](https://github.com/kotmatross28729/Shader-fixer/assets/110309314/7a464795-b608-45f5-bb43-f6ec6e6905bf)

**Comment by kotmatross28729** [comment]
**I still want to warn that some visual errors may occur** (red and blue highlight blocks, as well as lines may change brightness (a little), depending on the viewing angle), however they are in *most cases* not significant (and I can't do anything about it, since Schematica uses `glVertexPointer` and `quadVertexBuffer` for rendering and not `Tessellator.addVertex`, but I was able to get them to (at least) render))


Of the significant issues , I noticed that sometimes a water shader applies on the highlight blocks, but this is an exception for a couple of shaders (only noticed with Sildur's Enhanced Default ), if you use BSL then everything is fine

**Comment by kotmatross28729** [comment]
By the way, in 3.0 this will be fixed completely, that is, without changing the brightness at an viewing angle or applying a water shader.

 So the fix will be complete (3.0 coming soon™)
