### ISSUE TITLE
Request: compatibility with journeymap waypoint beacons

### ISSUE THREAD

**Issue by huihiuhuai** [kotmatross28729/Shader-fixer#3]

**Comment by kotmatross28729** [comment]
When adding a compatibility request, could you please attach a screenshot showing the error, or at least describe what exactly is wrong?
I just have to look for the problem further, which is why it takes more time.

Anyway, from what I could find:

* Fixed background rendering

* Fixed too bright icon rendering when used with some shaders


Before:

![2024-06-16_13 54 28](https://github.com/kotmatross28729/Shader-fixer/assets/110309314/a938a348-9d63-491d-b623-f719d3e4f71a)


After:

![2024-06-16_13 55 36](https://github.com/kotmatross28729/Shader-fixer/assets/110309314/96095664-60d1-4e76-89ff-3bf1338ebe60)
