### ISSUE TITLE
fixes don't apply to old shaders(Ziipzaap's Shaders V2)

### ISSUE THREAD

**Issue by huihiuhuai** [kotmatross28729/Shader-fixer#4]
Is the only way to fix the Ziipzaap's Shaders V2 that I'm testing, which were an edit of Chacopic13's Shaders, is to update the outdated shaders?

**Comment by kotmatross28729** [comment]
Strange, but now I tested with these shaders - everything works. Can you tell me which mod you are having a problem with (maybe there is just no patch for it on my side)? In any case, the use of old shaders is not recommended; they can sometimes cause bugs/errors where modern shaders (for example bsl, or complementary) don't have them

**Comment by huihiuhuai** [comment]
> Can you tell me which mod you are having a problem with
schematica, journey map, NEI

**Comment by huihiuhuai** [comment]
> I tested with these shaders

did you test with ziipzaap's shaders

**Comment by kotmatross28729** [comment]
> did you test with ziipzaap's shaders

yes, shaders - Ziipzaaps_Shaders_V2_Chocapic13_Shaders_edit

> schematica, journey map, NEI

Tested with all these mods - they work

**Comment by huihiuhuai** [comment]
currently don't have access to my laptop, but I can upload two screenshots and a mod list here. Can these be used to help address the problem?
![mmexport1719771171358](https://github.com/kotmatross28729/Shader-fixer/assets/166929082/8885a68e-d230-4d5d-8bfe-3812512edc2d)
shaders are sildurs vibrant v1.52 extreme
![mmexport1719771164838](https://github.com/kotmatross28729/Shader-fixer/assets/166929082/9efa0e21-534a-4e71-a8d1-dc5af1328473)
ziipzaaps shaders

modlist: https://pastebin.com/0AhCKrZA

**Comment by kotmatross28729** [comment]
Ah, now I see. In fact, the fix works, because without it, you wouldn't even see the frame of stone bricks and grass. And the fact that you don’t see the tree itself, is a problem with these particular shaders (they were developed primarily for the very old version of “GLSL Shaders”).  (if you are wondering what the problem is - ziipzaaps shaders, due to the fact that it was developed a long time ago and uses old technologies, overwrites the entire skybox completely + does it late enough for rendering, so the sky will always overlap any semi-transparent surfaces)

The solution is to simply use the new shaders (same, bsl, or complementary). They have settings, so if you are used to these specific shaders, you can configure bsl/complementary so that they look similar
